# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: gunicorn axmed_catalogue.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: axmed_db
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_contraseña
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A axmed_catalogue worker -B --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
